const std = @import("std");

pub const Basic = struct {
    ID: usize,
    Name: []const u8,
    Description: ?[]const u8,
    PackageBaseID: usize,
    PackageBase: []const u8,
    Maintainer: ?[]const u8,
    NumVotes: usize,
    Popularity: f32,
    FirstSubmitted: usize,
    LastModified: usize,
    OutOfDate: ?usize,
    Version: []const u8,
    URLPath: ?[]const u8,
    URL: ?[]const u8,
};

pub const Detailed = struct {
    ID: usize,
    Description: ?[]const u8,
    PackageBaseID: usize,
    PackageBase: []const u8,
    Maintainer: ?[]const u8,
    NumVotes: usize,
    Popularity: f32,
    FirstSubmitted: usize,
    LastModified: usize,
    OutOfDate: ?usize,
    Version: []const u8,
    URLPath: ?[]const u8,
    URL: ?[]const u8,
    License: [][]const u8,
    Depends: ?[][]const u8 = null,
    MakeDepends: ?[][]const u8 = null,
    OptDepends: ?[][]const u8 = null,
    CheckDepends: ?[][]const u8 = null,
    Provides: ?[][]const u8 = null,
    Conflicts: ?[][]const u8 = null,
    Replaces: ?[][]const u8 = null,
    Groups: ?[][]const u8 = null,
    Keywords: [][]const u8 = null,
    CoMaintainers: ?[][]const u8 = null,
};
